import Head from 'next/head'
import { useModalDialog } from '@/04_templates/useModalDialog'
import { BacklogItemForm } from '@/03_organisms/BacklogItemForm'

export default function Home() {
  const {ModalDialog, open, close} = useModalDialog()

return <>
    <Head>
      <title>Degino Backlog</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <button onClick={open}>ダイアログ</button>
    <ModalDialog>
      <BacklogItemForm isOpen={true} />
    </ModalDialog>
  </>
}
