import { useState } from 'react'
import Head from 'next/head'
import { Main } from '@/04_templates/MainPanel'
import { Kanban } from '@/03_organisms/Kanban'
import { Planning } from '@/03_organisms/Planning'
import { BacklogItemForm } from '@/03_organisms/BacklogItemForm'
import { Switcher } from '@/02_molecules/Switcher'

const menuItems = ['Planning', 'Kanban', 'UserStory'] // メニューリスト


export default function Home() {
  const [active, setActive] = useState(0)

  return <>
    <Head>
      <title>Degino Backlog</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <BacklogItemForm />
  </>
}
