import Head from 'next/head'
import { useState } from "react";
import { Kanban } from "@/03_organisms/Kanban";
import { Planning } from "@/03_organisms/Planning";
import { Main } from '@/04_templates/MainPanel';


//TODO:ボタンで二画面が切り替わること

//DONE:トグル式のボタン

export default function Home() {
  const [gamen, setGamen] = useState<string>("kanban")
  return (
    <>
      <Head>
        <title>Degino Backlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <div>
          <input
            type="radio"
            id="kanban"
            name="page"
            value="kanban"
            checked={gamen === "kanban"}
            onClick={() => { setGamen("kanban") }} />
          <label htmlFor="kanban">kanban</label>
        </div>
        <div>
          <input
            type="radio"
            id="planning"
            name="page"
            value="planning"
            checked={gamen === "planning"}
            onClick={() => { setGamen("planning") }} />
          <label htmlFor="planning">planning</label>
        </div>
        {gamen === "kanban" && <Kanban />}
        {gamen === "planning" && <Planning />}
      </Main>
    </>
  )
}
