import Head from 'next/head'
import { Kanban } from "@/03_organisms/Kanban";
import { Main } from '@/04_templates/MainPanel';

export default function Home() {
  return (
    <>
      <Head>
        <title>Degino Backlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>Kanban</h1>
        <Kanban />
      </Main>
    </>
  )
}
