import Head from 'next/head'
import PGoalKanban from "@/03_organisms/PGoalKanban";
import SGoalKanban from "@/03_organisms/SGoalKanban";
import ProductKanban from "@/03_organisms/ProductKanban";
import SprintKanban from "@/03_organisms/SprintKanban";
import { MainPanel } from '@/04_templates/MainPanel';

export default function Home() {
  return (
    <>
      <Head>
        <title>Degino Backlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPanel>
        <PGoalKanban />
        <SGoalKanban />
        <ProductKanban />
        <SprintKanban />
      </MainPanel>
    </>
  )
}
